### Numpy (Numerical Python)
- for fast operations 


#### Numpy Arrays



In [12]:
import numpy as ny
q=ny.array([2,4,6,0,67,8,23])
q

array([ 2,  4,  6,  0, 67,  8, 23])

In [13]:
type(q)

numpy.ndarray

In [21]:
l=[1,2,3,4,4,5]
q=[2,3,4,8,9,7]
h=list(map(lambda t1,t2:t1*t2,l,q))
h

[2, 6, 12, 32, 36, 35]

In [22]:
n1=ny.array(l)
n2=ny.array(q)
n1*n2

array([ 2,  6, 12, 32, 36, 35])

In [24]:
tw_d=ny.array([[1,2,3],[4,5,6]])
tw_d[1]

array([4, 5, 6])

In [25]:
tw_d[1,1]

5

In [30]:
tw_d[1,2],[2,2]

(6, [2, 2])

In [32]:
ny.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [35]:
ny.ones([2,2],dtype='int')

array([[1, 1],
       [1, 1]])

In [36]:
ny.zeros([2,4],dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
ny.full([10,20],2)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [38]:
ny.random.random(5)

array([0.45231363, 0.21134982, 0.86778893, 0.36361983, 0.04988748])

In [41]:
ny.random.randint(2,6,[5,10])

array([[4, 4, 3, 3, 5, 3, 5, 4, 2, 5],
       [2, 4, 4, 2, 2, 4, 4, 5, 4, 4],
       [4, 2, 2, 5, 2, 2, 3, 5, 5, 5],
       [4, 4, 2, 3, 2, 4, 3, 4, 5, 4],
       [2, 4, 5, 5, 5, 4, 2, 2, 3, 3]])

In [44]:
ny.eye(2,4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0]])

In [47]:
l=[i for i in range(1,1000000)]
m=[j**2 for j in range(1,1000000)]

import time
t1=time.time()
op=list(map(lambda x,y:x*y,l,m))
t2=time.time()

fi=t2-t1
fi

0.2656369209289551

In [59]:
ny.arange(2,6)

array([2, 3, 4, 5])

In [57]:
ny.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
q=ny.arange(1,25).reshape([4,3,2])
q[1:,:]

array([[[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [66]:
a1=ny.arange(1,13).reshape(4,3)
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
ny.tile([1,2,3],[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

## Pandas

In [68]:
import pandas as pd
k=pd.Series([1,5,9,4])
k

0    1
1    5
2    9
3    4
dtype: int64

In [70]:
m=pd.Series([23,45,67,89,23],['qwe','ert','try','yrt','et'])
m

qwe    23
ert    45
try    67
yrt    89
et     23
dtype: int64

In [71]:
m['et']

23

In [73]:
v=pd.DataFrame({'Name':['qw','we','rt'],'Sub No':[140001,140100,140200],'Grade':['A','A','A']})
v

Name  Sub No Grade
0   qw  140001     A
1   we  140100     A
2   rt  140200     A

In [78]:
m=pd.DataFrame([['wer','rte','tet','ert'],[1,2,3,4],[12,34,45,6],[23,5,67,9],[12,34,45,6],[23,5,67,9]])
m

0    1    2    3
0  wer  rte  tet  ert
1    1    2    3    4
2   12   34   45    6
3   23    5   67    9
4   12   34   45    6
5   23    5   67    9

#### create an array of 1's.
Take a list& convert in into a 3d array & add 1 to each element in an arry.

In [2]:
a=ny.ones([3,4],dtype="int")
list1=ny.arange(1,13)
con=list1.reshape(2,2,3)
add=con+1
print(add)

NameError: name 'ny' is not defined

In [3]:
a=ny.ones([3,4],dtype="int")
con=a.reshape(2,2,3)
add=con+1
print(add)

NameError: name 'ny' is not defined